update stable pipeline

diff --git a/.bluemix/pipeline_canary.yml b/.bluemix/pipeline_canary.yml
--- a/.bluemix/pipeline_canary.yml
+++ b/.bluemix/pipeline_canary.yml
@@ -52,7 +52,7 @@ stages:
     script: |
       #!/bin/bash
       # uncomment to debug the script
-      #set -x
+      # set -x
       # copy the script below into your app code repo (e.g. ./scripts/build_image.sh) and 'source' it from your pipeline job
       #    source ./scripts/build_image.sh
       # alternatively, you can source it from online script:
@@ -127,7 +127,7 @@ stages:
     script: |
       #!/bin/bash
       # uncomment to debug the script
-      #set -x
+      # set -x
       # copy the script below into your app code repo (e.g. ./scripts/check_predeploy.sh) and 'source' it from your pipeline job
       #    source ./scripts/check_predeploy_kubectl.sh
       # alternatively, you can source it from online script:
@@ -143,13 +143,32 @@ stages:
     build_type: shell
     script: |
       #!/bin/bash
+      # uncomment to debug the script
+      # set -x
 
-      export CANARY_DEPLOYMENT_NAME=$(yq r ${DEPLOYMENT_TEMPLATE} metadata.name)
+      # Identify canary
+      opsys=linux  # or darwin, or windows
+      curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest |\
+        grep browser_download |\
+        grep $opsys |\
+        cut -d '"' -f 4 |\
+        xargs curl -O -L
+      mv kustomize_*_${opsys}_amd64 /usr/local/bin/kustomize
+      chmod u+x /usr/local/bin/kustomize
+
+      export DEPLOYMENT_FILE=deploy.yaml
+      sed -i -e "s#iter8/reviews:istio-VERSION#$PIPELINE_IMAGE_URL#" ${PATCH_FILE}
+      sed -i -e "s#VERSION#${IMAGE_TAG}#g" ${PATCH_FILE}
+      cat ${PATCH_FILE}
+      kustomize build kustomize -o ${DEPLOYMENT_FILE}
+      cat ${DEPLOYMENT_FILE}
+
+      export CANARY_DEPLOYMENT_NAME=$(yq r ${DEPLOYMENT_FILE} metadata.name)
+      # Calculate the canary deployment name from the deployment template
+      echo "CANARY_DEPLOYMENT_NAME=${CANARY_DEPLOYMENT_NAME}"
 
       # If already defined build.properties from prior build job, append to it.
       cp build.properties $ARCHIVE_DIR/ || :
-
-      # IMAGE information from build.properties is used in Helm Chart deployment to set the release name
       echo "CANARY_DEPLOYMENT_NAME=${CANARY_DEPLOYMENT_NAME}" >> $ARCHIVE_DIR/build.properties
   - name: Deploy to Kubernetes
     type: deployer
@@ -161,7 +180,7 @@ stages:
     script: |
       #!/bin/bash
       # uncomment to debug the script
-      #set -x
+      # set -x
       # copy the script below into your app code repo (e.g. ./scripts/deploy_kubectl.sh) and 'source' it from your pipeline job
       #    source ./scripts/deploy_kubectl.sh
       # alternatively, you can source it from online script:
@@ -183,10 +202,6 @@ stages:
       kustomize build kustomize -o ${DEPLOYMENT_FILE}
       cat ${DEPLOYMENT_FILE}
 
-      echo "-------------------------------"
-      echo $CANARY_DEPLOYMENT_NAME
-      echo "-------------------------------"
-      
       USE_ISTIO_GATEWAY=true
       source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/deploy_kubectl.sh")
 - name: START CANARY EXPERIMENT (VIA ITER8)
@@ -213,6 +228,7 @@ stages:
     build_type: shell
     script: |-
       #!/bin/bash
+      # uncomment to debug the script
       # set -x
 
       # Calculate the experiment name from the experiment template file
@@ -223,10 +239,8 @@ stages:
       # Record name in build.properties so can use it to stop the experiment
       # If already defined build.properties from prior build job, append to it.
       cp build.properties $ARCHIVE_DIR/ || :
-
-      # IMAGE information from build.properties is used in Helm Chart deployment to set the release name
       echo "EXPERIMENT_NAME=${EXPERIMENT_NAME}" >> $ARCHIVE_DIR/build.properties
-  - name: Run iter8
+  - name: Start Experiment
     type: deployer
     target:
       api_key: ${API_KEY}
@@ -236,19 +250,21 @@ stages:
     script: |
       #!/bin/bash
       # uncomment to debug the script
-      #set -x
+      # set -x
 
-      echo "-------------------------------"
-      echo $CANARY_DEPLOYMENT_NAME
-      echo "-------------------------------"
+      # Identify baseline
+      export BASELINE_DEPLOYMENT_NAME=$(kubectl --namespace ${CLUSTER_NAMESPACE} get deploy --selector=$(kubectl --namespace ${CLUSTER_NAMESPACE} get dr --selector=iter8.tools/role=stable -o json | jq -r '.items[0].spec.subsets[] | select(.name == "stable") | .labels | to_entries[] | "\(.key)=\(.value)"' | paste -sd',' -) -o jsonpath='{.items[0].metadata.name}')
+      echo "BASELINE_DEPLOYMENT_NAME=${BASELINE_DEPLOYMENT_NAME}"
 
       # Run canary experiment using iter8
-      BASELINE_VERSION=reviews
+      BASELINE_VERSION=$BASELINE_DEPLOYMENT_NAME
+      echo "BASELINE_VERSION=$BASELINE_VERSION"
+      echo "CANARY_DEPLOYMENT_NAME=$CANARY_DEPLOYMENT_NAME"
       source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_experiment.sh")
 - name: DELETE CANARY VERSION
   inputs:
   - type: job
-    stage: START CANARY (VIA ITER8)
+    stage: START CANARY EXPERIMENT (VIA ITER8)
     job: Calculate Experiment Name
   triggers:
     - type: stage
@@ -271,11 +287,14 @@ stages:
     script: |
       #!/bin/bash
       # uncomment to debug the script
-      #set -x
+      # set -x
 
       # Stop iter8 experiment if still in progress
       echo "Stop iter8 experiment if still running"
-      kubectl --namespace ${CLUSTER_NAMESPACE} patch ${EXPERIMENT_NAME} --type=json -p '[{"op": "add", "path": "/spec/assessment", "value": "override_fail"}]'
+      kubectl --namespace ${CLUSTER_NAMESPACE} \
+        patch experiment ${EXPERIMENT_NAME} \
+        --type=json -p '[{"op": "add", "path": "/spec/assessment", "value": "override_success"}]' \
+      || true # don't fail when the experiment can't be found
   - name: Delete Deployment
     type: deployer
     target:
@@ -288,5 +307,5 @@ stages:
       # set -x
 
       echo "Delete canary deployment $DEPLOYMENT_NAME"
-      kubectl delete deployment ${DEPLOYMENT_NAME}-canary --namespace ${CLUSTER_NAMESPACE}
-      
+      kubectl delete deployment ${CANARY_DEPLOYMENT_NAME} --namespace ${CLUSTER_NAMESPACE}
+   
diff --git a/.bluemix/pipeline_stable.yml b/.bluemix/pipeline_stable.yml
--- a/.bluemix/pipeline_stable.yml
+++ b/.bluemix/pipeline_stable.yml
@@ -52,7 +52,7 @@ stages:
     script: |
       #!/bin/bash
       # uncomment to debug the script
-      #set -x
+      # set -x
       # copy the script below into your app code repo (e.g. ./scripts/build_image.sh) and 'source' it from your pipeline job
       #    source ./scripts/build_image.sh
       # alternatively, you can source it from online script:
@@ -93,7 +93,7 @@ stages:
 
       # Check for vulnerabilities of built image using Vulnerability Advisor
       source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_vulnerabilities.sh")
-- name: PROD
+- name: CHECK PREREQS
   inputs:
   - type: job
     stage: BUILD
@@ -104,32 +104,7 @@ stages:
   - name: buildprops
     value: build.properties
     type: file
-  - name: CLUSTER_NAMESPACE
-    value: ${PROD_CLUSTER_NAMESPACE}
-    type: text
-  - name: APP_URL
-    value: undefined
-    type: text   
   jobs:
-  - name: Pre-deploy check
-    type: deployer
-    target:
-      api_key: ${API_KEY}
-      region_id: ${PROD_REGION_ID}
-      resource_group: ${PROD_RESOURCE_GROUP}
-      kubernetes_cluster: ${PROD_CLUSTER_NAME}
-    script: |
-      #!/bin/bash
-      # uncomment to debug the script
-      #set -x
-      # copy the script below into your app code repo (e.g. ./scripts/check_predeploy.sh) and 'source' it from your pipeline job
-      #    source ./scripts/check_predeploy_kubectl.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_predeploy_kubectl.sh")
-
-      # Checks the cluster is ready, has a namespace configured with access to the private
-      # image registry (using an IBM Cloud API Key). It also configures Helm Tiller service to later perform a deploy with Helm.
-      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_predeploy_kubectl.sh")
   - name: Check Istio config
     type: deployer
     target:
@@ -149,14 +124,6 @@ stages:
 
       # Check Istio installation in target cluster
       source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/istio_check_install.sh")
-      
-      # copy the script below into your app code repo (e.g. ./scripts/config_istio_canary.sh) and 'source' it from your pipeline job
-      #    source ./scripts/config_istio_canary.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/config_istio_canary.sh")
-      
-      # Configure Istio gateway with a destination rule (stable/canary), and virtual service
-      source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/istio_config_canary.sh")
   - name: Check iter8 config
     type: deployer
     target:
@@ -175,7 +142,73 @@ stages:
 
       # Check Istio installation in target cluster
       source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/iter8_check_install.sh")
-  - name: Deploy to Kubernetes
+- name: START DEPLOY USING CANARY
+  inputs:
+  - type: job
+    stage: BUILD
+    job: Build Docker Image
+  triggers:
+    - type: stage
+  properties:
+  - name: buildprops
+    value: build.properties
+    type: file
+  - name: CLUSTER_NAMESPACE
+    value: ${PROD_CLUSTER_NAMESPACE}
+    type: text
+  - name: PATCH_FILE
+    value: kustomize/patch.yaml
+    type: text
+  - name: EXPERIMENT_TEMPLATE_FILE
+    value: iter8/experiment.yaml
+    type: text
+  - name: EXPERIMENT_NAME
+    value: 
+    type: text
+  - name: BASELINE_DEPLOYMENT_NAME
+    value: 
+    type: text
+  - name: CANARY_DEPLOYMENT_NAME
+    value: 
+    type: text
+  jobs:
+  - name: Prepare Experiment
+    type: builder
+    curatedDockerImage: latest
+    artifact_dir: ''
+    build_type: shell
+    script: |
+      #!/bin/bash
+      # uncomment to debug the script
+      # set -x
+
+      # Identify canary deployment name from the deployment yaml
+      # copy the script below into your app code repo (e.g. ./scripts/create_deployment.sh) and 'source' it from your pipeline job
+      #    source ./scripts/create_deployment.sh
+      # alternatively, you can source it from online script:
+      #    source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_deployment.sh")
+      # Create canary deployment yaml
+      source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_deployment.sh")
+
+      export CANARY_DEPLOYMENT_NAME=$(yq r ${DEPLOYMENT_FILE} metadata.name)
+      echo "CANARY_DEPLOYMENT_NAME=${CANARY_DEPLOYMENT_NAME}"
+
+      # Identify experiment name to use
+      if [ -z "${EXPERIMENT_TEMPLATE_FILE}" ]; then EXPERIMENT_TEMPLATE_FILE=iter8_experiment.yaml ; fi
+      if [ ! -f ${EXPERIMENT_TEMPLATE_FILE} ]; then
+        echo -e "${red}iter8 experiment template '${EXPERIMENT_TEMPLATE_FILE}' not found${no_color}"
+      fi
+
+      export EXPERIMENT_NAME=$(yq read ${EXPERIMENT_TEMPLATE_FILE} metadata.name)-${BUILD_NUMBER}
+      echo "EXPERIMENT_NAME=${EXPERIMENT_NAME}"
+
+      # Record names in build.properties for use by later stages
+      #   append to existing build.properties if already defined
+      cp build.properties $ARCHIVE_DIR/ || :
+      echo "BASELINE_DEPLOYMENT_NAME=${BASELINE_DEPLOYMENT_NAME}" >> $ARCHIVE_DIR/build.properties
+      echo "CANARY_DEPLOYMENT_NAME=${CANARY_DEPLOYMENT_NAME}" >> $ARCHIVE_DIR/build.properties
+      echo "EXPERIMENT_NAME=${EXPERIMENT_NAME}" >> $ARCHIVE_DIR/build.properties
+  - name: Start Experiment
     type: deployer
     target:
       api_key: ${API_KEY}
@@ -185,14 +218,82 @@ stages:
     script: |
       #!/bin/bash
       # uncomment to debug the script
-      #set -x
+      # set -x
+
+      # Identify baseline deploymet
+      export BASELINE_DEPLOYMENT_NAME=$(kubectl --namespace ${CLUSTER_NAMESPACE} get deploy --selector=$(kubectl --namespace ${CLUSTER_NAMESPACE} get dr --selector=iter8.tools/role=stable -o json | jq -r '.items[0].spec.subsets[] | select(.name == "stable") | .labels | to_entries[] | "\(.key)=\(.value)"' | paste -sd',' -) -o jsonpath='{.items[0].metadata.name}') || true
+      if [[ -z "${BASELINE_DEPLOYMENT_NAME}" ]]; then
+        BASELINE_DEPLOYMENT_NAME="${CANARY_DEPLOYMENT_NAME}"
+      fi
+ 
+      # Run canary experiment using iter8
+      echo "BASELINE_DEPLOYMENT_NAME=${BASELINE_DEPLOYMENT_NAME}"
+      echo "CANARY_DEPLOYMENT_NAME=$CANARY_DEPLOYMENT_NAME"
+      ON_SUCCESS=canary
+      source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_experiment.sh")
+- name: DEPLOY
+  inputs:
+  - type: job
+    stage: BUILD
+    job: Build Docker image
+  triggers:
+  - type: stage
+  properties:
+  - name: buildprops
+    value: build.properties
+    type: file
+  - name: CLUSTER_NAMESPACE
+    value: ${PROD_CLUSTER_NAMESPACE}
+    type: text
+  - name: APP_URL
+    value: undefined
+    type: text   
+  - name: PATCH_FILE
+    value: kustomize/patch.yaml
+    type: text
+  jobs:
+  - name: Pre-deploy check
+    type: deployer
+    target:
+      api_key: ${API_KEY}
+      region_id: ${PROD_REGION_ID}
+      resource_group: ${PROD_RESOURCE_GROUP}
+      kubernetes_cluster: ${PROD_CLUSTER_NAME}
+    script: |
+      #!/bin/bash
+      # uncomment to debug the script
+      # set -x
+      # copy the script below into your app code repo (e.g. ./scripts/check_predeploy.sh) and 'source' it from your pipeline job
+      #    source ./scripts/check_predeploy_kubectl.sh
+      # alternatively, you can source it from online script:
+      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_predeploy_kubectl.sh")
+
+      # Checks the cluster is ready, has a namespace configured with access to the private
+      # image registry (using an IBM Cloud API Key). It also configures Helm Tiller service to later perform a deploy with Helm.
+      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_predeploy_kubectl.sh")
+  - name: Deploy to Kubernetes
+    type: deployer
+    target:
+      api_key: ${API_KEY}
+      region_id: ${PROD_REGION_ID}
+      resource_group: ${PROD_RESOURCE_GROUP}
+      kubernetes_cluster: ${PROD_CLUSTER_NAME}
+    script: |
+      # uncomment to debug the script
+      # set -x
+      # copy the script below into your app code repo (e.g. ./scripts/create_deployment.sh) and 'source' it from your pipeline job
+      #    source ./scripts/create_deployment.sh
+      # alternatively, you can source it from online script:
+      #    source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_deployment.sh")
+      # Create canary deployment yaml
+      source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_deployment.sh")
+
       # copy the script below into your app code repo (e.g. ./scripts/deploy_kubectl.sh) and 'source' it from your pipeline job
       #    source ./scripts/deploy_kubectl.sh
       # alternatively, you can source it from online script:
       #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/deploy_kubectl.sh")
-
+      # Create canary deployment yaml
       USE_ISTIO_GATEWAY=true
-      # Perform a kubectl deploy of container image and check on outcome
       source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/deploy_kubectl.sh")
   - name: Health check
     type: deployer
@@ -211,4 +312,51 @@ stages:
       #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_health.sh")
 
       # Check liveness and readiness probes to confirm application is healthy
-      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_health.sh")    
+      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_health.sh")
+- name: DELETE ORIGINAL VERSION
+  inputs:
+  - type: job
+    stage: START DEPLOY USING CANARY
+    job: Prepare Experiment
+  triggers:
+    - type: stage
+      enabled: false
+  properties:
+  - name: buildprops
+    value: build.properties
+    type: file
+  - name: CLUSTER_NAMESPACE
+    value: ${PROD_CLUSTER_NAMESPACE}
+    type: text
+  jobs:
+  - name: Stop Experiment
+    type: deployer
+    target:
+      api_key: ${API_KEY}
+      region_id: ${PROD_REGION_ID}
+      resource_group: ${PROD_RESOURCE_GROUP}
+      kubernetes_cluster: ${PROD_CLUSTER_NAME}
+    script: |
+      #!/bin/bash
+      # uncomment to debug the script
+      # set -x
+
+      # Stop iter8 experiment if still in progress
+      echo "Stop iter8 experiment if still running"
+      kubectl --namespace ${CLUSTER_NAMESPACE} \
+        patch experiment ${EXPERIMENT_NAME} \
+        --type=json -p '[{"op": "add", "path": "/spec/assessment", "value": "override_success"}]' \
+      || true # don't fail when the experiment can't be found
+  - name: Delete Deployment
+    type: deployer
+    target:
+      region_id: ${PROD_REGION_ID}
+      api_key: ${API_KEY}
+      kubernetes_cluster: ${PROD_CLUSTER_NAME}
+    script: |
+      #!/bin/bash
+      # uncomment to debug the script
+      # set -x
+
+      echo "Delete canary deployment $BASELINE_DEPLOYMENT_NAME"
+      kubectl delete deployment ${BASELINE_DEPLOYMENT_NAME} --namespace ${CLUSTER_NAMESPACE}
