refine canary after stable

diff --git a/.bluemix/pipeline_canary.yml b/.bluemix/pipeline_canary.yml
--- a/.bluemix/pipeline_canary.yml
+++ b/.bluemix/pipeline_canary.yml
@@ -93,6 +93,95 @@ stages:
 
       # Check for vulnerabilities of built image using Vulnerability Advisor
       source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_vulnerabilities.sh")
+- name: CONFIGURE CANARY
+  inputs:
+  - type: job
+    stage: BUILD
+    job: Build Docker image
+  triggers:
+  - type: stage
+  properties:
+  - name: buildprops
+    value: build.properties
+    type: file
+  - name: CLUSTER_NAMESPACE
+    value: ${PROD_CLUSTER_NAMESPACE}
+    type: text
+  - name: PATCH_FILE
+    value: kustomize/patch.yaml
+    type: text
+  - name: EXPERIMENT_TEMPLATE_FILE
+    value: iter8/experiment.yaml
+    type: text
+  - name: EXPERIMENT_NAME
+    value: 
+    type: text
+  - name: BASELINE_DEPLOYMENT_NAME
+    value: 
+    type: text
+  - name: CANARY_DEPLOYMENT_NAME
+    value: 
+    type: text
+  jobs:
+  - name: Prepare Experiment
+    type: builder
+    curatedDockerImage: latest
+    artifact_dir: ''
+    build_type: shell
+    script: |
+      #!/bin/bash
+      # uncomment to debug the script
+      # set -x
+
+      # Identify canary deployment name from the deployment yaml
+      # copy the script below into your app code repo (e.g. ./scripts/create_deployment.sh) and 'source' it from your pipeline job
+      #    source ./scripts/create_deployment.sh
+      # alternatively, you can source it from online script:
+      #    source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_deployment.sh")
+      # Create canary deployment yaml
+      source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_deployment.sh")
+
+      export CANARY_DEPLOYMENT_NAME=$(yq r ${DEPLOYMENT_FILE} metadata.name)
+      echo "CANARY_DEPLOYMENT_NAME=${CANARY_DEPLOYMENT_NAME}"
+
+      # Identify experiment name to use
+      if [ -z "${EXPERIMENT_TEMPLATE_FILE}" ]; then EXPERIMENT_TEMPLATE_FILE=iter8_experiment.yaml ; fi
+      if [ ! -f ${EXPERIMENT_TEMPLATE_FILE} ]; then
+        echo -e "${red}iter8 experiment template '${EXPERIMENT_TEMPLATE_FILE}' not found${no_color}"
+      fi
+
+      export EXPERIMENT_NAME=$(yq read ${EXPERIMENT_TEMPLATE_FILE} metadata.name)-${BUILD_NUMBER}
+      echo "EXPERIMENT_NAME=${EXPERIMENT_NAME}"
+
+      # Record names in build.properties for use by later stages
+      #   append to existing build.properties if already defined
+      cp build.properties $ARCHIVE_DIR/ || :
+      echo "BASELINE_DEPLOYMENT_NAME=${BASELINE_DEPLOYMENT_NAME}" >> $ARCHIVE_DIR/build.properties
+      echo "CANARY_DEPLOYMENT_NAME=${CANARY_DEPLOYMENT_NAME}" >> $ARCHIVE_DIR/build.properties
+      echo "EXPERIMENT_NAME=${EXPERIMENT_NAME}" >> $ARCHIVE_DIR/build.properties
+  - name: Start Experiment
+    type: deployer
+    target:
+      api_key: ${API_KEY}
+      region_id: ${PROD_REGION_ID}
+      resource_group: ${PROD_RESOURCE_GROUP}
+      kubernetes_cluster: ${PROD_CLUSTER_NAME}
+    script: |
+      #!/bin/bash
+      # uncomment to debug the script
+      # set -x
+
+      # Identify baseline deploymet
+      export BASELINE_DEPLOYMENT_NAME=$(kubectl --namespace ${CLUSTER_NAMESPACE} get deploy --selector=$(kubectl --namespace ${CLUSTER_NAMESPACE} get dr --selector=iter8.tools/role=stable -o json | jq -r '.items[0].spec.subsets[] | select(.name == "stable") | .labels | to_entries[] | "\(.key)=\(.value)"' | paste -sd',' -) -o jsonpath='{.items[0].metadata.name}') || true
+      if [[ -z "${BASELINE_DEPLOYMENT_NAME}" ]]; then
+        BASELINE_DEPLOYMENT_NAME="${CANARY_DEPLOYMENT_NAME}"
+      fi
+ 
+      # Run canary experiment using iter8
+      echo "BASELINE_DEPLOYMENT_NAME=${BASELINE_DEPLOYMENT_NAME}"
+      echo "CANARY_DEPLOYMENT_NAME=$CANARY_DEPLOYMENT_NAME"
+      ON_SUCCESS=baseline
+      source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_experiment.sh")
 - name: DEPLOY
   inputs:
   - type: job
@@ -107,14 +196,8 @@ stages:
   - name: CLUSTER_NAMESPACE
     value: ${PROD_CLUSTER_NAMESPACE}
     type: text    
-  - name: DEPLOYMENT_TEMPLATE
-    value: kustomize/deployment.yaml
-    type: text
   - name: PATCH_FILE
     value: kustomize/patch.yaml
-    type: text
-  - name: DEPLOYMENT_FILE
-    value: kustomize/deployment.yaml
     type: text
   jobs:
   - name: Pre-deploy check
@@ -136,40 +219,6 @@ stages:
       # Checks the cluster is ready, has a namespace configured with access to the private
       # image registry (using an IBM Cloud API Key). It also configures Helm Tiller service to later perform a deploy with Helm.
       source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_predeploy_kubectl.sh")
-  - name: Compute Canary Name
-    type: builder
-    curatedDockerImage: latest
-    artifact_dir: ''
-    build_type: shell
-    script: |
-      #!/bin/bash
-      # uncomment to debug the script
-      # set -x
-
-      # Identify canary
-      opsys=linux  # or darwin, or windows
-      curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest |\
-        grep browser_download |\
-        grep $opsys |\
-        cut -d '"' -f 4 |\
-        xargs curl -O -L
-      mv kustomize_*_${opsys}_amd64 /usr/local/bin/kustomize
-      chmod u+x /usr/local/bin/kustomize
-
-      export DEPLOYMENT_FILE=deploy.yaml
-      sed -i -e "s#iter8/reviews:istio-VERSION#$PIPELINE_IMAGE_URL#" ${PATCH_FILE}
-      sed -i -e "s#VERSION#${IMAGE_TAG}#g" ${PATCH_FILE}
-      cat ${PATCH_FILE}
-      kustomize build kustomize -o ${DEPLOYMENT_FILE}
-      cat ${DEPLOYMENT_FILE}
-
-      export CANARY_DEPLOYMENT_NAME=$(yq r ${DEPLOYMENT_FILE} metadata.name)
-      # Calculate the canary deployment name from the deployment template
-      echo "CANARY_DEPLOYMENT_NAME=${CANARY_DEPLOYMENT_NAME}"
-
-      # If already defined build.properties from prior build job, append to it.
-      cp build.properties $ARCHIVE_DIR/ || :
-      echo "CANARY_DEPLOYMENT_NAME=${CANARY_DEPLOYMENT_NAME}" >> $ARCHIVE_DIR/build.properties
   - name: Deploy to Kubernetes
     type: deployer
     target:
@@ -178,94 +227,27 @@ stages:
       resource_group: ${PROD_RESOURCE_GROUP}
       kubernetes_cluster: ${PROD_CLUSTER_NAME}
     script: |
-      #!/bin/bash
       # uncomment to debug the script
       # set -x
+      # copy the script below into your app code repo (e.g. ./scripts/create_deployment.sh) and 'source' it from your pipeline job
+      #    source ./scripts/create_deployment.sh
+      # alternatively, you can source it from online script:
+      #    source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_deployment.sh")
+      # Create canary deployment yaml
+      source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_deployment.sh")
+
       # copy the script below into your app code repo (e.g. ./scripts/deploy_kubectl.sh) and 'source' it from your pipeline job
       #    source ./scripts/deploy_kubectl.sh
       # alternatively, you can source it from online script:
       #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/deploy_kubectl.sh")
-
-      opsys=linux  # or darwin, or windows
-      curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest |\
-        grep browser_download |\
-        grep $opsys |\
-        cut -d '"' -f 4 |\
-        xargs curl -O -L
-      mv kustomize_*_${opsys}_amd64 /usr/local/bin/kustomize
-      chmod u+x /usr/local/bin/kustomize
-
-      export DEPLOYMENT_FILE=deploy.yaml
-      sed -i -e "s#iter8/reviews:istio-VERSION#$PIPELINE_IMAGE_URL#" ${PATCH_FILE}
-      sed -i -e "s#VERSION#${IMAGE_TAG}#g" ${PATCH_FILE}
-      cat ${PATCH_FILE}
-      kustomize build kustomize -o ${DEPLOYMENT_FILE}
-      cat ${DEPLOYMENT_FILE}
-
+      # Create canary deployment yaml
       USE_ISTIO_GATEWAY=true
       source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/deploy_kubectl.sh")
-- name: START CANARY EXPERIMENT (VIA ITER8)
-  inputs:
-  - type: job
-    stage: DEPLOY
-    job: Compute Canary Name
-  triggers:
-    - type: stage
-      enabled: false
-  properties:
-  - name: buildprops
-    value: build.properties
-    type: file
-  - name: CLUSTER_NAMESPACE
-    value: ${PROD_CLUSTER_NAMESPACE}
-    type: text
-  - name: EXPERIMENT_TEMPLATE_FILE
-    value: iter8/experiment.yaml
-    type: text
-  jobs:
-  - name: Calculate Experiment Name
-    type: builder
-    build_type: shell
-    script: |-
-      #!/bin/bash
-      # uncomment to debug the script
-      # set -x
-
-      # Calculate the experiment name from the experiment template file
-      echo "EXPERIMENT_TEMPLATE_FILE=${EXPERIMENT_TEMPLATE_FILE}"
-      export EXPERIMENT_NAME=$(yq read ${EXPERIMENT_TEMPLATE_FILE} metadata.name)-${BUILD_NUMBER}
-      echo "EXPERIMENT_NAME=${EXPERIMENT_NAME}"
-
-      # Record name in build.properties so can use it to stop the experiment
-      # If already defined build.properties from prior build job, append to it.
-      cp build.properties $ARCHIVE_DIR/ || :
-      echo "EXPERIMENT_NAME=${EXPERIMENT_NAME}" >> $ARCHIVE_DIR/build.properties
-  - name: Start Experiment
-    type: deployer
-    target:
-      api_key: ${API_KEY}
-      region_id: ${PROD_REGION_ID}
-      resource_group: ${PROD_RESOURCE_GROUP}
-      kubernetes_cluster: ${PROD_CLUSTER_NAME}
-    script: |
-      #!/bin/bash
-      # uncomment to debug the script
-      # set -x
-
-      # Identify baseline
-      export BASELINE_DEPLOYMENT_NAME=$(kubectl --namespace ${CLUSTER_NAMESPACE} get deploy --selector=$(kubectl --namespace ${CLUSTER_NAMESPACE} get dr --selector=iter8.tools/role=stable -o json | jq -r '.items[0].spec.subsets[] | select(.name == "stable") | .labels | to_entries[] | "\(.key)=\(.value)"' | paste -sd',' -) -o jsonpath='{.items[0].metadata.name}')
-      echo "BASELINE_DEPLOYMENT_NAME=${BASELINE_DEPLOYMENT_NAME}"
-
-      # Run canary experiment using iter8
-      BASELINE_VERSION=$BASELINE_DEPLOYMENT_NAME
-      echo "BASELINE_VERSION=$BASELINE_VERSION"
-      echo "CANARY_DEPLOYMENT_NAME=$CANARY_DEPLOYMENT_NAME"
-      source <(curl -sSL "https://raw.githubusercontent.com/kalantar/canary-testing-istio-toolchain/master/scripts/create_experiment.sh")
 - name: DELETE CANARY VERSION
   inputs:
   - type: job
-    stage: START CANARY EXPERIMENT (VIA ITER8)
-    job: Calculate Experiment Name
+    stage: CONFIGURE CANARY
+    job: Prepare Experiment
   triggers:
     - type: stage
       enabled: false
